# -*- coding: utf-8 -*-
"""Petit réseau.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQB8rJUkCBnRiy0tX7BpJ3Mpg699J-C8

**Section 1 : Mise en place**

Cette section importe les modules nécessaires pour créer et manipuler notre réseau de neurones.

Vous n'avez besoin d'exécuter cette section qu'**une seule fois**, au tout début de l'activité.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, Subset
import matplotlib.pyplot as plt

# 1. Define transformations (Convert image to Tensor and Normalize)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

"""**Section 2 : Configuration du réseau**

Cette section sert à définir les paramètres de votre réseau et de son entrainement.

À chaque fois que vous voulez modifier le réseau, vous devez :

1.   modifier les paramètres dans cette section;
2.   exécuter cette section
1.   exécuter la section suivante.
"""

chiffres_a_identifer = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # (classes)
nombre_de_couches_cachees = 1  # hidden layers
nombre_de_neurones_par_couche_cachee = 32  # neurons per hidden layer
nombre_depoques = 6  # epoch count

"""**Section 3 : Entrainement et test**

Cette section prépare le réseau tel que configuré à la section 2.

Puis, le réseau est entrainé sur les données d'entrainement.

Finalement, la précision du réseau est vérifiée avec les données de test.

En sortie, le code présente jusqu'à 8 exemples d'images pour lesquelles le réseau a fait une prédiction erronée.
"""

# @title
# 2. Download MNIST
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)


def filter_numbers(dataset):
    indices = dataset.targets == chiffres_a_identifer[0]
    dataset.targets[dataset.targets == chiffres_a_identifer[0]] = 0
    for ii, chiffre in enumerate(chiffres_a_identifer[1:]):
        indices = indices | (dataset.targets == chiffre)
        dataset.targets[dataset.targets == chiffre] = ii + 1
    return Subset(dataset, torch.where(indices)[0])


train_subset = filter_numbers(train_dataset)
test_subset = filter_numbers(test_dataset)

train_loader = DataLoader(train_subset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_subset, batch_size=32, shuffle=False)


class FlexibleNet(nn.Module):
    def __init__(self, num_hidden_layers=1, hidden_size=128, output_size=2):
        super(FlexibleNet, self).__init__()

        self.hidden_layers = nn.ModuleList()

        # 1. Input Layer (784 -> hidden_size)
        self.input_layer = nn.Linear(784, hidden_size)

        # 2. Add 'n' Hidden Layers (hidden_size -> hidden_size)
        for _ in range(num_hidden_layers):
            self.hidden_layers.append(nn.Linear(hidden_size, hidden_size))

        # 3. Output Layer (hidden_size -> 2)
        self.output_layer = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = x.view(-1, 784)
        x = torch.relu(self.input_layer(x))

        # Loop through our list of hidden layers
        for layer in self.hidden_layers:
            x = torch.relu(layer(x))

        x = self.output_layer(x)
        return x


# Example: Create a model with 5 hidden layers
model = FlexibleNet(nombre_de_couches_cachees, nombre_de_neurones_par_couche_cachee, len(chiffres_a_identifer))
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(nombre_depoques):
    model.train()
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    print(f"Époque {epoch + 1} terminée. Perte : {loss.item():.4f}")

model.eval()
correct = 0
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        correct += (predicted == labels).sum().item()

print(f"Précision avec les données tests : {round(100 * correct / len(test_subset), 2)}%")

# 1. Put model in evaluation mode
model.eval()

misclassified_images = []
true_labels = []
predicted_labels = []

# 2. Loop through the test data to find mistakes
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        # Find where predictions don't match the labels
        errors = (predicted != labels)

        if errors.any():
            misclassified_images.extend(images[errors])
            true_labels.extend(labels[errors])
            predicted_labels.extend(predicted[errors])

# 3. Display the results
if len(misclassified_images) > 0:
    print(f"Nombre d'images mal classifiées : {len(misclassified_images)}")
    plt.figure(figsize=(12, 5))

    # Show up to the first 5 errors
    num_to_display = min(len(misclassified_images), 8)
    for i in range(num_to_display):
        plt.subplot(1, num_to_display, i + 1)

        # Undo normalization for clear viewing: (pixel * std) + mean
        img = misclassified_images[i].squeeze() * 0.3081 + 0.1307

        plt.imshow(img, cmap='gray')
        plt.title(f"True: {chiffres_a_identifer[true_labels[i]]}\nPred: {chiffres_a_identifer[predicted_labels[i]]}")
        plt.axis('off')
    plt.show()
else:
    print("Aucune erreur dans l'ensemble de test. Bravo!")
